Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - Gemfile
    - tmp/**/*
    - node_modules/**/*
    - log/*
    - docker/*

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

Layout/AlignHash:
  Exclude:
    - spec/models/user_spec.rb
Layout/CommentIndentation:
  Exclude:
    - spec/spec_helper.rb

Lint/IneffectiveAccessModifier:
  Exclude:
    - lib/tasks/post_published_tweet.rb
Lint/UriEscapeUnescape:
  Exclude:
    - app/controllers/v1/posts_controller.rb

Metrics/AbcSize:
  Max: 26
  Exclude:
    - lib/tasks/write_secrets_in_env.rb

# ブロック内の長さ
Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 105

# 一行の長さ
Metrics/LineLength:
  Max: 160

# メソッド名の長さ
Metrics/MethodLength:
  Max: 30

Naming/AccessorMethodName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

# find_by でカラムを指定して使用する
Rails/DynamicFindBy:
  Enabled: false
Rails/FilePath:
  Exclude:
    - spec/rails_helper.rb
Rails/FindBy:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/TimeZone:
  Enabled: false

# 出力の指定
Rails/Output:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# DateTime の使用
Style/DateTime:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# !! の使用
Style/DoubleNegation:
  Enabled: false

# 文字列リテラルに対し、マジックコメントを使用していること
Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Exclude:
    - app/controllers/application_controller.rb
    - app/controllers/posts_controller.rb
    - app/helpers/sessions_helper.rb

Style/IfUnlessModifier:
  Exclude:
    - app/controllers/application_controller.rb
    - app/controllers/posts_controller.rb

Style/Lambda:
  Enabled: false

# 文字列リテラルであればシングルクォートを推奨する
Style/StringLiterals:
  Enabled: false
