FROM ruby:4.0.1 

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential \
    git \
    curl \
    ca-certificates \
    tzdata \
    default-mysql-client \
    nodejs \
  && rm -rf /var/lib/apt/lists/*

ENV TZ=Asia/Tokyo

WORKDIR /app

ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install

ADD . /app
